### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by yusuf-khamis** [davidroman0O/moleculer-socketio#2]
Your documentation is not comprehensive enough, I had to look at the code to write a proper service, also, the code in your documentation is not well-formatted, just good idea, good work, but crappy documentation, please just consider working on that.
On service reload during debugging, it looks like the server is not well shut down, I had to call `this.io.close()` manually inside `stopped` function. Also, consider improving the code, might fork when I get time

**Comment by davidroman0O** [comment]
It's an opensource project on my spare time.

Don't except people to code for free and to be at your service.

`might fork when I get time` 
Then do that
